"""empty message

Revision ID: 107629da4697
Revises: 4d64c3152243
Create Date: 2023-10-08 12:40:59.529337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107629da4697'
down_revision = '4d64c3152243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screenshot', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('screenshot', 'url',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('similars', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('similars', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('screenshot', 'url',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('screenshot', 'name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
