"""empty message

Revision ID: 1ba4a9d6a29b
Revises: 
Create Date: 2023-12-02 19:53:58.065462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba4a9d6a29b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agelimit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agelimit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agelimit_name'), ['name'], unique=True)

    op.create_table('country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_name'), ['name'], unique=True)

    op.create_table('creator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_name'), ['name'], unique=True)

    op.create_table('director',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_director_name'), ['name'], unique=True)

    op.create_table('filmlength',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genre_name'), ['name'], unique=True)

    op.create_table('ratingfilmcritics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratingimdb',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratingkinopoisk',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('star', sa.Float(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reliase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('screenshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinopoisk_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshot_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshot_url'), ['url'], unique=False)

    op.create_table('similars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinopoisk_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('similars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_similars_name'), ['name'], unique=False)

    op.create_table('tagactor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tagactor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tagactor_name'), ['name'], unique=False)

    op.create_table('trailer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('background', sa.String(length=256), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trailer_background'), ['background'], unique=False)
        batch_op.create_index(batch_op.f('ix_trailer_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_trailer_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_trailer_url'), ['url'], unique=False)

    op.create_table('typevideo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('typevideo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_typevideo_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tagactor.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_name'), ['name'], unique=True)

    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kinopoisk_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=12), nullable=True),
    sa.Column('name_ru', sa.String(length=256), nullable=True),
    sa.Column('name_original', sa.String(length=256), nullable=True),
    sa.Column('poster_url', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('rating_kinopoisk_id', sa.Integer(), nullable=True),
    sa.Column('rating_imdb_id', sa.Integer(), nullable=True),
    sa.Column('rating_critics_id', sa.Integer(), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('film_length_id', sa.Integer(), nullable=True),
    sa.Column('slogan', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('type_video_id', sa.Integer(), nullable=True),
    sa.Column('age_limits_id', sa.Integer(), nullable=True),
    sa.Column('last_syncs', sa.DateTime(), nullable=True),
    sa.Column('countries_id', sa.Integer(), nullable=True),
    sa.Column('genres_id', sa.Integer(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('screen_img_id', sa.Integer(), nullable=True),
    sa.Column('similar_id', sa.Integer(), nullable=True),
    sa.Column('trailer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['age_limits_id'], ['agelimit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['countries_id'], ['country.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['film_length_id'], ['filmlength.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['genres_id'], ['genre.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rating_critics_id'], ['ratingfilmcritics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rating_imdb_id'], ['ratingimdb.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rating_kinopoisk_id'], ['ratingkinopoisk.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screen_img_id'], ['screenshot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['similar_id'], ['similars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailer.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_video_id'], ['typevideo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['year_id'], ['reliase.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_actor',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('tagactor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['tagactor_id'], ['tagactor.id'], )
    )
    op.create_table('actor_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('country_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('creator_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('director_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('genre_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('screenshot_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('screenshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshot.id'], )
    )
    op.create_table('similars_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('similars_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['similars_id'], ['similars.id'], )
    )
    op.create_table('trailer_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('trailer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['trailer_id'], ['trailer.id'], )
    )
    op.create_table('user_movie',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie')
    op.drop_table('trailer_movie')
    op.drop_table('similars_movie')
    op.drop_table('screenshot_movie')
    op.drop_table('genre_movie')
    op.drop_table('director_movie')
    op.drop_table('creator_movie')
    op.drop_table('country_movie')
    op.drop_table('actor_movie')
    op.drop_table('tag_actor')
    op.drop_table('movie')
    op.drop_table('roles_users')
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_name'))

    op.drop_table('actor')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('typevideo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_typevideo_name'))

    op.drop_table('typevideo')
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trailer_url'))
        batch_op.drop_index(batch_op.f('ix_trailer_type'))
        batch_op.drop_index(batch_op.f('ix_trailer_name'))
        batch_op.drop_index(batch_op.f('ix_trailer_background'))

    op.drop_table('trailer')
    with op.batch_alter_table('tagactor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tagactor_name'))

    op.drop_table('tagactor')
    with op.batch_alter_table('similars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_similars_name'))

    op.drop_table('similars')
    with op.batch_alter_table('screenshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenshot_url'))
        batch_op.drop_index(batch_op.f('ix_screenshot_name'))

    op.drop_table('screenshot')
    op.drop_table('roles')
    op.drop_table('reliase')
    op.drop_table('ratingkinopoisk')
    op.drop_table('ratingimdb')
    op.drop_table('ratingfilmcritics')
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_name'))

    op.drop_table('genre')
    op.drop_table('filmlength')
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_director_name'))

    op.drop_table('director')
    with op.batch_alter_table('creator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_name'))

    op.drop_table('creator')
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_name'))

    op.drop_table('country')
    with op.batch_alter_table('agelimit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agelimit_name'))

    op.drop_table('agelimit')
    # ### end Alembic commands ###
