"""empty message

Revision ID: 2fcffeb56007
Revises: e492d5127db6
Create Date: 2023-12-24 19:23:30.388772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcffeb56007'
down_revision = 'e492d5127db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agelimit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_old', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_agelimit_name')
        batch_op.create_index(batch_op.f('ix_agelimit_name_old'), ['name_old'], unique=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agelimit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_agelimit_name_old'))
        batch_op.create_index('ix_agelimit_name', ['name'], unique=False)
        batch_op.drop_column('name_old')

    # ### end Alembic commands ###
