"""empty message

Revision ID: 55556b86a857
Revises: 107629da4697
Create Date: 2023-10-08 16:01:46.100841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55556b86a857'
down_revision = '107629da4697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('trailer', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'trailer')
    # ### end Alembic commands ###
