"""empty message

Revision ID: efc93dbfdb9a
Revises: 01beae44200d
Create Date: 2023-12-23 15:28:17.194645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc93dbfdb9a'
down_revision = '01beae44200d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['roles_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('roles_id')

    # ### end Alembic commands ###
