
services:
    flask-postgres:
        container_name: flask_postgres
        image: postgres:16
        restart: always
        env_file:
            - ./app/.env
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
#            - ./postgres/backup:/home/backup
            - ./postgres/database:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - flask_app_network

    flask-app:
        container_name: flask_app
        build: ./app
        environment:
            DB_HOST: flask-postgres
            DB_PORT: 5432
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASS}
        entrypoint: ["sh", "./entrypoint.sh"]
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - flask-postgres
        volumes:
            - ./app:/home/app
#            - ./app/app/static:/app/app/static
            - ./postgres/backup:/home/backup
        networks:
            - flask_app_network

    flask-nginx:
        container_name: flask_nginx
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        command: "/bin/sh /nginx-autoreload.sh"
        volumes:
            - ./app/app/static:/app/staticfiles
            - ./nginx/nginx-autoreload.sh:/nginx-autoreload.sh
            #            - ./nginx/conf_dev/:/etc/nginx/conf.d/:ro
            #      - ./nginx/conf_prod/:/etc/nginx/conf.d/:ro
            #      - ./nginx/ssl_https:/home/ssl_https
        environment:
            - FLASK_PORT=${FLASK_PORT:?error missing FLASK_PORT env}
        depends_on:
            - flask-app
        networks:
            - flask_app_network
        restart: always

    movie-parser:
        container_name: movie_parser
        build: ./kinopoisk
        env_file:
            - ./kinopoisk/.env
        entrypoint: [ "sh", "./entrypoint.sh" ]
        depends_on:
            - flask-app
        volumes:
            - ./app/app/static:/home/app/static
        networks:
            - flask_app_network

#    wireguard-vpn:
#        image: linuxserver/wireguard
#        container_name: wireguard
#        cap_add:
#            - NET_ADMIN
##            - SYS_MODULE
#        environment:
#            - PUID=1000          # UID пользователя
#            - PGID=1000          # GID пользователя
##            - PEERS=client1
##            - IPTABLES_BACKEND=legacy  # или просто отключить iptables
##            - ENABLE_IPTABLES=false
#        volumes:
#            - ./wireguard/config/WireGuardProtonVpn-US-FREE-41.conf:/config/wg_confs/wg0.conf
#        ports:
#            - "5021:51820/udp"
#        sysctls:
#            - net.ipv4.conf.all.src_valid_mark=1
#        restart: unless-stopped
#        networks:
#            - flask_app_network


networks:
  flask_app_network:
    driver: bridge
