bade_status_codes = {
    400: "Bad Request («неправильный, некорректный запрос»)",
    401: "Unauthorized («не авторизован (не представился)»)",
    402: "Payment Required («необходима оплата»)",
    403: "Forbidden («запрещено (не уполномочен)»)",
    404: "Not Found («не найдено»)",
    408: "Request Timeout («истекло время ожидания»)",
    423: "Locked («заблокировано»);",
    429: "Too Many Requests («слишком много запросов»)",
    499: "Client Closed Request (клиент закрыл соединение)",

    500: "Internal Server Error («внутренняя ошибка сервера»)",
    502: "Bad Gateway («плохой, ошибочный шлюз»)",
    503: "Service Unavailable («сервис недоступен»)",
    504: "Gateway Timeout («шлюз не отвечает»)",
    520: "Unknown Error («неизвестная ошибка»)",
    521: "Web Server Is Down («веб-сервер не работает»)",
    522: "Connection Timed Out («соединение не отвечает»)",
    523: "Origin Is Unreachable («источник недоступен»)",
    524: "A Timeout Occurred («время ожидания истекло»)",
}